### ISSUE TITLE
wireshark: command not found

### ISSUE THREAD

**Issue by scottkelso** [iwaseyusuke/docker-mininet#2]
Apologies if this is a silly question but I'm not sure how to run Wireshark.  This docker container doesn't seem to have it.  I have tried the wireshark command at all the different levels...

>$ docker exec -it fa3a7eeaed5a /bin/sh
> .# wireshark
>/bin/sh: 1: wireshark: not found

>root@fa3a7eeaed5a:~# wireshark
>bash: wireshark: command not found

>mininet> wireshark
>*** Unknown command: wireshark

I got it working with xming and VirtualBox on Windows 10 a while back but switched to Ubuntu and Docker because of other dependencies.  Does Wireshark need installed natively?

Currently running Ubuntu:16.04 and Docker:18.03.1-ce

**Comment by iwaseyusuke** [comment]
@scottkelso Hi, thanks for using this Docker image!

Unfortunately, I don't include `wireshark` in this image (`tcpdump` is install though). For the included packages, please refer to [`Dockerfile`](https://github.com/iwaseyusuke/docker-mininet/blob/master/Dockerfile).

For installing `wireshark`, please install it via `apt-get` command.
```bash
root@204de83c4f37:~# apt-get update && apt-get install -y wireshark
...(snip)...
```

Also, if you face to the following error message,
```bash
root@204de83c4f37:~# wireshark 
No protocol specified
QXcbConnection: Could not connect to display :0
Aborted (core dumped)
```
please add `root` user to the access control list of `xhost` on "Docker host" (not on container).
```bash
$ xhost +si:localuser:root
localuser:root being added to access control list
```

**Comment by scottkelso** [comment]
Thank you @iwaseyusuke. That was the exact error I got yesterday. Cheers.

**Comment by iwaseyusuke** [comment]
@scottkelso Thunks for your confirmation! Happy hacking!
