### ISSUE TITLE
xterm not running

### ISSUE THREAD

**Issue by scottkelso** [iwaseyusuke/docker-mininet#4]
Is there a workaround for not having the ability to run `xterm` commands?

```
mininet> xterm h1
mininet>
```

And no new window opens - which I assume is because mininet is in a docker container?

Currently running this image on Ubuntu:16.04 and docker:18.03.1-ce
Any suggestions would be greatly appreciated!

**Comment by iwaseyusuke** [comment]
@scottkelso Hi again! Similar to the https://github.com/iwaseyusuke/docker-mininet/issues/2#issuecomment-398242242, please try;
```bash
xhost +si:localuser:root
```
on your Docker host.

For example, on my environment, before invoking this command;
```bash
root@26f36691a400:~# xterm
No protocol specified
Warning: This program is an suid-root program or is being run by the root user.
The full text of the error or warning message cannot be safely formatted
in this environment. You may get a more descriptive message by running the
program as a non-root user or by removing the suid bit on the executable.
xterm: Xt error: Can't open display: %s
```
and after calling this command;
```bash
root@26f36691a400:~# xterm
(a new xterm window was opened)
```

**Comment by scottkelso** [comment]
Ah yes that was it.  Thanks again for correcting my silly mistake!
