### ISSUE TITLE
Problem with xterm

### ISSUE THREAD

**Issue by himkwtn** [iwaseyusuke/docker-mininet#6]
What should the variable DISPLAY be?
I set `DISPLAY=:0` and when I run `xhost +si:localhost:root` I got this error
`xhost:  unable to open display ":0"`

I'm running this image on macOS HighSierra 10.13.6

**Comment by himkwtn** [comment]
I didn't read the instruction properly. I was supposed to run that command on the host. 
However, it still didn't work and I fixed it by running `xhost +` instead and set `DISPLAY=host.docker.internal:0`

**Comment by iwaseyusuke** [comment]
@himkwtn Thank you for trying this image!
Sorry, I didn't try on macOS. But just guessing, on macOS, X11 Window System is not running, so xhost cannot connect to any display server. Please try it on X11 enabled OS.
(macOS has XQuartz though, it seems to be no longer maintained actively...)
