### ISSUE TITLE
Support for CMD

### ISSUE THREAD

**Issue by tbarbette** [iwaseyusuke/docker-mininet#9]
It would be great if passing an argument to the docker run command would launch mininet directly, so it can be used in scripts. For instance : 
```
sudo docker run -it --rm --privileged -e DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v /lib/modules:/lib/modules iwaseyusuke/mininet --topo=linear
```

**Comment by iwaseyusuke** [comment]
@tbarbette Thanks a lot for your great idea!
[PR#10 ](https://github.com/iwaseyusuke/docker-mininet/pull/10) should work as you proposed!

**Comment by tbarbette** [comment]
That's perfect, thanks!
